obj-m += gwe_rs232.o

all:
	make -C /lib/modules/3.1.9+/build M=/root/COM_addon/kernel-driver/tutorial modules

clean:
	make -C /lib/modules/3.1.9+/build M=/root/COM_addon/kernel-driver/tutorial clean
